### ISSUE TITLE
Default Storage Path not a good idea

### ISSUE THREAD

**Issue by bneigher** [robwalkerco/redux-persist-filesystem-storage#44] opened 2019-10-04 19:34 UTC
I'm seeing that ya'll are setting the defaultStoragePath to
```
const defaultStoragePath = `${RNFetchBlob.fs.dirs.DocumentDir}/persistStore`
```

Which is then used as the config for rn-fetch-blob.

Correct me if I'm wrong, but this means that on every app update (at least on iOS) the storage will become severed from the next version of the app since DocumentDir is a UUID that is generated from the app release.

The effect is that each time the app updates the storage is marooned, and a new empty state from redux-persist will begin...

I may be incorrect here, but if anyone else is noticing this happening (maybe it's just on TestFlight?) I would suggest changing the `defaultStoragePath` to either be a static directory, or something we can pass into as a config for redux-persist-filesystem-storage.

For now, I'm going to build a migration that checks if prevDocumentDir !== DocumentDir, and if so - mv the files to the new directory.. this is wacko and shouldn't be something a developer should need to do IMO

**Comment by ChrisLFieldsII** [comment] 2019-11-05 21:33
This is something I had not thought about until reading this!

I did a quick search to see if its possible to write into the filesystem at a static path but I don't think this is possible for security reasons. I found [this](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html) archived documentation that seems to confirm that.

Sounds like your solution is the best way to handle this problem

**Comment by solace** [comment] 2020-02-02 03:23
@bneigher, I stumbled across this looking for something else. I had a problem related to this as well but with Async-Storage, and had made an enquiry about it on the expo forums, specifically this comment (https://forums.expo.io/t/documentdir-when-migrating-from-expokit-to-react-native-init-app/29155/4)

I don't know if it will help you, but another user confirmed that the UUID should not change because it's based on vendor and bundle ID.

As I couldn't get this working reliably to my satisfaction in TestFlight, and being paranoid, I actually soft-released my app, mucked around with the data, then bumped the version to confirm the data didn't vanish. If you're prepared to do that, it will at least give you peace of mind that it is working predictably.

**Comment by robwalkerco** [comment] 2020-07-30 20:54
I'm closing this issue as I don't believe this is a valid issue.
However, please reopen if it does continue to be a problem, and the cause can be attributed back to this library.

**Closed by robwalkerco** 2020-07-30 20:54 UTC
